name: First Workflow

on: push

jobs:
  first_job:
    runs_on: ubuntu-latest
    steps:
    - name: Hello Github Actions
      run: echo "First Github Actions Job"

    - name: List files
      run: ls

    - name: Read file
      run: cat README.mdF
